name: SysDVRClient
options:
  bundleIdPrefix: com.lu
  deploymentTarget:
    iOS: "15.0"
  useBaseInternationalization: false
targets:
  SysDVRClient:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: SysDVRClient
    settings:
      PRODUCT_NAME: SysDVRClient
      SWIFT_VERSION: "5.9"
      SWIFT_OBJC_BRIDGING_HEADER: ""
      GCC_TREAT_WARNINGS_AS_ERRORS: "NO"
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      SUPPORTS_MACCATALYST: "NO"
      DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: "NO"
      SDKROOT: iphoneos
      TARGETED_DEVICE_FAMILY: "1,2"
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"
    info:
      path: SysDVRClient/Info.plist
      properties:
        UIMainStoryboardFile: ""
        NSLocalNetworkUsageDescription: "SysDVR needs local network access to connect to your Nintendo Switch"
        NSBonjourServices:
          - _services._dns-sd._udp
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
